apiVersion: kubeadm.k8s.io/v1beta2
kind: ClusterConfiguration
#kubernetesVersion: 1.21.1
kubernetesVersion: 1.20.0
controlPlaneEndpoint: "k8smaster:6443"
networking:
  podSubnet: 10.10.0.0/16
apiServer:
  extraArgs:
    advertise-address: 192.168.50.100
