Vagrant.configure("2") do |config|


  # MASTER NODE
  config.vm.define "master" do |master|
    master.vm.box = "ubuntu/bionic64"
    #master.vm.box = "debian/stretch64"
    #TO CHANGE DISK SIZE INSTALL PLUGIN: vagrant plugin install vagrant-disksize
    #master.disksize.size = '15GB'
    
    master.vm.hostname = "MASTER"
    master.vm.network "private_network", ip: "192.168.50.100", virtualbox__intnet: true
    master.vm.network :forwarded_port, guest: 22, host: 2225
    master.vm.network :forwarded_port, guest: 22, host: 2235
    master.vm.network :forwarded_port, guest: 22, host: 2245
    master.vm.network :forwarded_port, guest: 22, host: 2255
    master.vm.network "private_network", ip: "192.168.56.100"

    master.vm.box_check_update = false

    if Vagrant.has_plugin?("vagrant-vbguest") then
      master.vbguest.auto_update = false
      #master.vbguest.no_install  = true
    end

    # Customize the amount of memory and cpu on the VM:
    master.vm.provider "virtualbox" do |vb|
      vb.memory = "6000"
      vb.cpus = 3
      # enable promiscuous mode on the public network
      vb.customize ["modifyvm", :id, "--nicpromisc2", "allow-all"]
    end

    # some user configs
    master.vm.provision "file", source: "./gitconfig", destination: "/home/vagrant/.gitconfig"
    master.vm.provision "file", source: "./vimrc", destination: "/home/vagrant/.vimrc"
    master.vm.provision "file", source: "./tmux", destination: "/home/vagrant/.tmux.conf"
      
    # k8s installation    
    master.vm.provision "shell", path: "install_pkgs.sh"
    master.vm.provision "shell", path: "install_k8s_master.sh"
  end


  # WORKER NODE
  config.vm.define "worker" do |worker|
    worker.vm.box = "ubuntu/bionic64"
    #worker.vm.box = "debian/stretch64"
    #TO CHANGE DISK SIZE INSTALL PLUGIN: vagrant plugin install vagrant-disksize
    #worker.disksize.size = '15GB'
    
    worker.vm.hostname = "worker"
    worker.vm.network "private_network", ip: "192.168.50.101", virtualbox__intnet: true
    worker.vm.network :forwarded_port, guest: 22, host: 2224

    worker.vm.box_check_update = false

    if Vagrant.has_plugin?("vagrant-vbguest") then
      worker.vbguest.auto_update = false
      #worker.vbguest.no_install  = true
    end

    # Customize the amount of memory and cpu on the VM:
    worker.vm.provider "virtualbox" do |vb|
      vb.memory = "3000"
      vb.cpus = 2
      # enable promiscuous mode on the public network
      vb.customize ["modifyvm", :id, "--nicpromisc2", "allow-all"]
    end

    # some user configs
    worker.vm.provision "file", source: "./gitconfig", destination: "/home/vagrant/.gitconfig"
    worker.vm.provision "file", source: "./vimrc", destination: "/home/vagrant/.vimrc"
    worker.vm.provision "file", source: "./tmux", destination: "/home/vagrant/.tmux.conf"

    # k8s installation    
    worker.vm.provision "shell", path: "install_pkgs.sh"
    worker.vm.provision "shell", path: "install_k8s_worker.sh"
  end

end

# Extra Vagrant configuration
load File.expand_path("Vagrantfile.extra") if File.exists?("Vagrantfile.extra")